// src/tools/common/periodic-table/elements.ts
// 元素周期表数据 - 118 个元素

export interface Element {
  number: number
  symbol: string
  name: string
  nameEn: string
  category: ElementCategory
  atomicMass: number
  period: number
  group: number
  block: string
  electronConfig: string
  electronegativity?: number
  density?: number
  meltingPoint?: number
  boilingPoint?: number
  discoveredBy?: string
  yearDiscovered?: number
  funFact: string
  row: number
  col: number
}

export type ElementCategory =
  | 'alkali-metal'
  | 'alkaline-earth'
  | 'transition-metal'
  | 'post-transition'
  | 'metalloid'
  | 'nonmetal'
  | 'halogen'
  | 'noble-gas'
  | 'lanthanide'
  | 'actinide'

export const categoryColors: Record<ElementCategory, string> = {
  'alkali-metal': '#ff6b6b',
  'alkaline-earth': '#ffa94d',
  'transition-metal': '#ffd43b',
  'post-transition': '#69db7c',
  'metalloid': '#38d9a9',
  'nonmetal': '#4dabf7',
  'halogen': '#748ffc',
  'noble-gas': '#da77f2',
  'lanthanide': '#f783ac',
  'actinide': '#e599f7',
}

export const categoryNames: Record<ElementCategory, string> = {
  'alkali-metal': '碱金属',
  'alkaline-earth': '碱土金属',
  'transition-metal': '过渡金属',
  'post-transition': '后过渡金属',
  'metalloid': '准金属',
  'nonmetal': '非金属',
  'halogen': '卤素',
  'noble-gas': '稀有气体',
  'lanthanide': '镧系元素',
  'actinide': '锕系元素',
}

export const elements: Element[] = [
  {
    number: 1, symbol: 'H', name: '氢', nameEn: 'Hydrogen',
    category: 'nonmetal', atomicMass: 1.008, period: 1, group: 1, block: 's',
    electronConfig: '1s¹', electronegativity: 2.20, density: 0.00008988,
    meltingPoint: -259.16, boilingPoint: -252.87,
    discoveredBy: 'Henry Cavendish', yearDiscovered: 1766,
    funFact: '氢是宇宙中最丰富的元素，占宇宙质量的约 75%！',
    row: 1, col: 1,
  },
  {
    number: 2, symbol: 'He', name: '氦', nameEn: 'Helium',
    category: 'noble-gas', atomicMass: 4.003, period: 1, group: 18, block: 's',
    electronConfig: '1s²', density: 0.0001785,
    meltingPoint: -272.2, boilingPoint: -268.93,
    discoveredBy: 'Pierre Janssen', yearDiscovered: 1868,
    funFact: '氦是在太阳上发现的，比地球早 17 年！氦气球会让人声音变尖。',
    row: 1, col: 18,
  },
  {
    number: 3, symbol: 'Li', name: '锂', nameEn: 'Lithium',
    category: 'alkali-metal', atomicMass: 6.941, period: 2, group: 1, block: 's',
    electronConfig: '[He] 2s¹', electronegativity: 0.98, density: 0.534,
    meltingPoint: 180.54, boilingPoint: 1342,
    discoveredBy: 'Johan August Arfwedson', yearDiscovered: 1817,
    funFact: '锂是最轻的金属，可以浮在水面上！也用于治疗双相情感障碍。',
    row: 2, col: 1,
  },
  {
    number: 4, symbol: 'Be', name: '铍', nameEn: 'Beryllium',
    category: 'alkaline-earth', atomicMass: 9.012, period: 2, group: 2, block: 's',
    electronConfig: '[He] 2s²', electronegativity: 1.57, density: 1.85,
    meltingPoint: 1287, boilingPoint: 2469,
    discoveredBy: 'Louis Nicolas Vauquelin', yearDiscovered: 1798,
    funFact: '铍是透明的 X 射线窗口材料，也是绿宝石的主要成分！',
    row: 2, col: 2,
  },
  {
    number: 5, symbol: 'B', name: '硼', nameEn: 'Boron',
    category: 'metalloid', atomicMass: 10.81, period: 2, group: 13, block: 'p',
    electronConfig: '[He] 2s² 2p¹', electronegativity: 2.04, density: 2.34,
    meltingPoint: 2076, boilingPoint: 3927,
    discoveredBy: 'Joseph Louis Gay-Lussac', yearDiscovered: 1808,
    funFact: '硼砂是清洁剂的重要成分，硼纤维比钢还强但更轻！',
    row: 2, col: 13,
  },
  {
    number: 6, symbol: 'C', name: '碳', nameEn: 'Carbon',
    category: 'nonmetal', atomicMass: 12.011, period: 2, group: 14, block: 'p',
    electronConfig: '[He] 2s² 2p²', electronegativity: 2.55, density: 2.267,
    meltingPoint: 3550, boilingPoint: 4027,
    funFact: '碳是生命的基石，可以形成钻石（最硬）或石墨（很软），同一种元素竟然如此不同！',
    row: 2, col: 14,
  },
  {
    number: 7, symbol: 'N', name: '氮', nameEn: 'Nitrogen',
    category: 'nonmetal', atomicMass: 14.007, period: 2, group: 15, block: 'p',
    electronConfig: '[He] 2s² 2p³', electronegativity: 3.04, density: 0.0012506,
    meltingPoint: -210.1, boilingPoint: -195.79,
    discoveredBy: 'Daniel Rutherford', yearDiscovered: 1772,
    funFact: '空气的 78% 是氮气！液氮温度低至 -196°C，可以瞬间冷冻食物。',
    row: 2, col: 15,
  },
  {
    number: 8, symbol: 'O', name: '氧', nameEn: 'Oxygen',
    category: 'nonmetal', atomicMass: 15.999, period: 2, group: 16, block: 'p',
    electronConfig: '[He] 2s² 2p⁴', electronegativity: 3.44, density: 0.001429,
    meltingPoint: -218.79, boilingPoint: -182.96,
    discoveredBy: 'Carl Wilhelm Scheele', yearDiscovered: 1771,
    funFact: '氧气占空气的 21%，是地球上大部分生命必需的。纯氧环境下铁可以燃烧！',
    row: 2, col: 16,
  },
  {
    number: 9, symbol: 'F', name: '氟', nameEn: 'Fluorine',
    category: 'halogen', atomicMass: 18.998, period: 2, group: 17, block: 'p',
    electronConfig: '[He] 2s² 2p⁵', electronegativity: 3.98, density: 0.001696,
    meltingPoint: -219.67, boilingPoint: -188.11,
    discoveredBy: 'André-Marie Ampère', yearDiscovered: 1810,
    funFact: '氟是电负性最强的元素，几乎所有元素都能和它反应！牙膏里的氟化物能保护牙齿。',
    row: 2, col: 17,
  },
  {
    number: 10, symbol: 'Ne', name: '氖', nameEn: 'Neon',
    category: 'noble-gas', atomicMass: 20.180, period: 2, group: 18, block: 'p',
    electronConfig: '[He] 2s² 2p⁶', density: 0.0008999,
    meltingPoint: -248.59, boilingPoint: -246.08,
    discoveredBy: 'William Ramsay', yearDiscovered: 1898,
    funFact: '氖气通电会发出橙红色的光，这就是霓虹灯的原理！"霓虹"就是 Neon 的音译。',
    row: 2, col: 18,
  },
  {
    number: 11, symbol: 'Na', name: '钠', nameEn: 'Sodium',
    category: 'alkali-metal', atomicMass: 22.990, period: 3, group: 1, block: 's',
    electronConfig: '[Ne] 3s¹', electronegativity: 0.93, density: 0.971,
    meltingPoint: 97.79, boilingPoint: 882.94,
    discoveredBy: 'Humphry Davy', yearDiscovered: 1807,
    funFact: '钠遇到水会剧烈反应甚至爆炸！食盐就是钠和氯的化合物。',
    row: 3, col: 1,
  },
  {
    number: 12, symbol: 'Mg', name: '镁', nameEn: 'Magnesium',
    category: 'alkaline-earth', atomicMass: 24.305, period: 3, group: 2, block: 's',
    electronConfig: '[Ne] 3s²', electronegativity: 1.31, density: 1.738,
    meltingPoint: 650, boilingPoint: 1091,
    discoveredBy: 'Joseph Black', yearDiscovered: 1755,
    funFact: '镁燃烧时发出耀眼的白光，闪光灯和烟花都用到它！叶绿素的核心就是镁。',
    row: 3, col: 2,
  },
  {
    number: 13, symbol: 'Al', name: '铝', nameEn: 'Aluminium',
    category: 'post-transition', atomicMass: 26.982, period: 3, group: 13, block: 'p',
    electronConfig: '[Ne] 3s² 3p¹', electronegativity: 1.61, density: 2.698,
    meltingPoint: 660.32, boilingPoint: 2519,
    discoveredBy: 'Hans Christian Ørsted', yearDiscovered: 1825,
    funFact: '铝是地壳中含量最丰富的金属元素。曾经铝比黄金还贵，因为提炼太难了！',
    row: 3, col: 13,
  },
  {
    number: 14, symbol: 'Si', name: '硅', nameEn: 'Silicon',
    category: 'metalloid', atomicMass: 28.086, period: 3, group: 14, block: 'p',
    electronConfig: '[Ne] 3s² 3p²', electronegativity: 1.90, density: 2.3296,
    meltingPoint: 1414, boilingPoint: 3265,
    discoveredBy: 'Jöns Jacob Berzelius', yearDiscovered: 1824,
    funFact: '硅是计算机芯片的基础材料，硅谷因此得名！沙子的主要成分就是二氧化硅。',
    row: 3, col: 14,
  },
  {
    number: 15, symbol: 'P', name: '磷', nameEn: 'Phosphorus',
    category: 'nonmetal', atomicMass: 30.974, period: 3, group: 15, block: 'p',
    electronConfig: '[Ne] 3s² 3p³', electronegativity: 2.19, density: 1.82,
    meltingPoint: 44.15, boilingPoint: 280.5,
    discoveredBy: 'Hennig Brand', yearDiscovered: 1669,
    funFact: '磷是第一个被发现的元素！白磷在黑暗中会发光，"磷光"这个词就是这么来的。',
    row: 3, col: 15,
  },
  {
    number: 16, symbol: 'S', name: '硫', nameEn: 'Sulfur',
    category: 'nonmetal', atomicMass: 32.06, period: 3, group: 16, block: 'p',
    electronConfig: '[Ne] 3s² 3p⁴', electronegativity: 2.58, density: 2.067,
    meltingPoint: 115.21, boilingPoint: 444.6,
    funFact: '硫燃烧时产生蓝色火焰和刺鼻气味。火山口附近常有硫磺结晶，非常漂亮！',
    row: 3, col: 16,
  },
  {
    number: 17, symbol: 'Cl', name: '氯', nameEn: 'Chlorine',
    category: 'halogen', atomicMass: 35.45, period: 3, group: 17, block: 'p',
    electronConfig: '[Ne] 3s² 3p⁵', electronegativity: 3.16, density: 0.003214,
    meltingPoint: -101.5, boilingPoint: -34.04,
    discoveredBy: 'Carl Wilhelm Scheele', yearDiscovered: 1774,
    funFact: '氯气曾被用作化学武器，但氯也是消毒和净化水的重要元素！',
    row: 3, col: 17,
  },
  {
    number: 18, symbol: 'Ar', name: '氩', nameEn: 'Argon',
    category: 'noble-gas', atomicMass: 39.948, period: 3, group: 18, block: 'p',
    electronConfig: '[Ne] 3s² 3p⁶', density: 0.0017837,
    meltingPoint: -189.34, boilingPoint: -185.85,
    discoveredBy: 'Lord Rayleigh', yearDiscovered: 1894,
    funFact: '氩占空气的 0.93%，是空气中含量最多的稀有气体。灯泡里填充氩气可以延长寿命。',
    row: 3, col: 18,
  },
  {
    number: 19, symbol: 'K', name: '钾', nameEn: 'Potassium',
    category: 'alkali-metal', atomicMass: 39.098, period: 4, group: 1, block: 's',
    electronConfig: '[Ar] 4s¹', electronegativity: 0.82, density: 0.862,
    meltingPoint: 63.38, boilingPoint: 759,
    discoveredBy: 'Humphry Davy', yearDiscovered: 1807,
    funFact: '钾遇到水会燃烧并发出紫色火焰！香蕉富含钾，是很好的补充来源。',
    row: 4, col: 1,
  },
  {
    number: 20, symbol: 'Ca', name: '钙', nameEn: 'Calcium',
    category: 'alkaline-earth', atomicMass: 40.078, period: 4, group: 2, block: 's',
    electronConfig: '[Ar] 4s²', electronegativity: 1.00, density: 1.55,
    meltingPoint: 842, boilingPoint: 1484,
    discoveredBy: 'Humphry Davy', yearDiscovered: 1808,
    funFact: '钙是骨骼和牙齿的主要成分，人体中 99% 的钙都在骨骼里！',
    row: 4, col: 2,
  },
  {
    number: 21, symbol: 'Sc', name: '钪', nameEn: 'Scandium',
    category: 'transition-metal', atomicMass: 44.956, period: 4, group: 3, block: 'd',
    electronConfig: '[Ar] 3d¹ 4s²', electronegativity: 1.36, density: 2.989,
    meltingPoint: 1541, boilingPoint: 2836,
    discoveredBy: 'Lars Fredrik Nilson', yearDiscovered: 1879,
    funFact: '钪用于制造高性能运动器材，如自行车架和棒球棒，又轻又强！',
    row: 4, col: 3,
  },
  {
    number: 22, symbol: 'Ti', name: '钛', nameEn: 'Titanium',
    category: 'transition-metal', atomicMass: 47.867, period: 4, group: 4, block: 'd',
    electronConfig: '[Ar] 3d² 4s²', electronegativity: 1.54, density: 4.506,
    meltingPoint: 1668, boilingPoint: 3287,
    discoveredBy: 'William Gregor', yearDiscovered: 1791,
    funFact: '钛的强度和钢相当，但重量只有钢的 60%！人体不会排斥钛，所以用于人工关节。',
    row: 4, col: 4,
  },
  {
    number: 23, symbol: 'V', name: '钒', nameEn: 'Vanadium',
    category: 'transition-metal', atomicMass: 50.942, period: 4, group: 5, block: 'd',
    electronConfig: '[Ar] 3d³ 4s²', electronegativity: 1.63, density: 6.11,
    meltingPoint: 1910, boilingPoint: 3407,
    discoveredBy: 'Andrés Manuel del Río', yearDiscovered: 1801,
    funFact: '钒化合物有各种美丽的颜色，名字来源于北欧女神 Vanadis（爱神弗雷亚）。',
    row: 4, col: 5,
  },
  {
    number: 24, symbol: 'Cr', name: '铬', nameEn: 'Chromium',
    category: 'transition-metal', atomicMass: 51.996, period: 4, group: 6, block: 'd',
    electronConfig: '[Ar] 3d⁵ 4s¹', electronegativity: 1.66, density: 7.15,
    meltingPoint: 1907, boilingPoint: 2671,
    discoveredBy: 'Louis Nicolas Vauquelin', yearDiscovered: 1797,
    funFact: '铬的名字来自希腊语"颜色"，因为它的化合物五彩缤纷！不锈钢就是因为含铬。',
    row: 4, col: 6,
  },
  {
    number: 25, symbol: 'Mn', name: '锰', nameEn: 'Manganese',
    category: 'transition-metal', atomicMass: 54.938, period: 4, group: 7, block: 'd',
    electronConfig: '[Ar] 3d⁵ 4s²', electronegativity: 1.55, density: 7.44,
    meltingPoint: 1246, boilingPoint: 2061,
    discoveredBy: 'Johan Gottlieb Gahn', yearDiscovered: 1774,
    funFact: '锰是钢铁生产的必需添加剂，能让钢更坚硬。高锰酸钾是紫色的消毒剂。',
    row: 4, col: 7,
  },
  {
    number: 26, symbol: 'Fe', name: '铁', nameEn: 'Iron',
    category: 'transition-metal', atomicMass: 55.845, period: 4, group: 8, block: 'd',
    electronConfig: '[Ar] 3d⁶ 4s²', electronegativity: 1.83, density: 7.874,
    meltingPoint: 1538, boilingPoint: 2862,
    funFact: '铁是地球核心的主要成分！血红蛋白中的铁让血液呈红色，也是氧气运输的关键。',
    row: 4, col: 8,
  },
  {
    number: 27, symbol: 'Co', name: '钴', nameEn: 'Cobalt',
    category: 'transition-metal', atomicMass: 58.933, period: 4, group: 9, block: 'd',
    electronConfig: '[Ar] 3d⁷ 4s²', electronegativity: 1.88, density: 8.9,
    meltingPoint: 1495, boilingPoint: 2927,
    discoveredBy: 'Georg Brandt', yearDiscovered: 1735,
    funFact: '钴蓝色玻璃和陶瓷的蓝色都来自钴！维生素 B12 的核心就是钴。',
    row: 4, col: 9,
  },
  {
    number: 28, symbol: 'Ni', name: '镍', nameEn: 'Nickel',
    category: 'transition-metal', atomicMass: 58.693, period: 4, group: 10, block: 'd',
    electronConfig: '[Ar] 3d⁸ 4s²', electronegativity: 1.91, density: 8.902,
    meltingPoint: 1455, boilingPoint: 2913,
    discoveredBy: 'Axel Fredrik Cronstedt', yearDiscovered: 1751,
    funFact: '美国五分硬币叫"nickel"，因为含有 25% 的镍。镍过敏是很常见的金属过敏。',
    row: 4, col: 10,
  },
  {
    number: 29, symbol: 'Cu', name: '铜', nameEn: 'Copper',
    category: 'transition-metal', atomicMass: 63.546, period: 4, group: 11, block: 'd',
    electronConfig: '[Ar] 3d¹⁰ 4s¹', electronegativity: 1.90, density: 8.96,
    meltingPoint: 1084.62, boilingPoint: 2562,
    funFact: '铜是人类最早使用的金属之一！铜导电性极好，电线都用铜。铜绿让自由女神像变绿。',
    row: 4, col: 11,
  },
  {
    number: 30, symbol: 'Zn', name: '锌', nameEn: 'Zinc',
    category: 'transition-metal', atomicMass: 65.38, period: 4, group: 12, block: 'd',
    electronConfig: '[Ar] 3d¹⁰ 4s²', electronegativity: 1.65, density: 7.134,
    meltingPoint: 419.53, boilingPoint: 907,
    discoveredBy: 'Andreas Sigismund Marggraf', yearDiscovered: 1746,
    funFact: '锌是人体必需的微量元素，缺锌会影响味觉和免疫力。镀锌可以防止铁生锈。',
    row: 4, col: 12,
  },
  {
    number: 31, symbol: 'Ga', name: '镓', nameEn: 'Gallium',
    category: 'post-transition', atomicMass: 69.723, period: 4, group: 13, block: 'p',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹', electronegativity: 1.81, density: 5.907,
    meltingPoint: 29.76, boilingPoint: 2204,
    discoveredBy: 'Paul Emile Lecoq de Boisbaudran', yearDiscovered: 1875,
    funFact: '镓的熔点只有 29.76°C，放在手心就会融化！但沸点很高，温差超过 2000°C。',
    row: 4, col: 13,
  },
  {
    number: 32, symbol: 'Ge', name: '锗', nameEn: 'Germanium',
    category: 'metalloid', atomicMass: 72.630, period: 4, group: 14, block: 'p',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p²', electronegativity: 2.01, density: 5.323,
    meltingPoint: 938.25, boilingPoint: 2833,
    discoveredBy: 'Clemens Winkler', yearDiscovered: 1886,
    funFact: '锗是早期晶体管的材料，开启了电子时代。光纤通信中也用到锗。',
    row: 4, col: 14,
  },
  {
    number: 33, symbol: 'As', name: '砷', nameEn: 'Arsenic',
    category: 'metalloid', atomicMass: 74.922, period: 4, group: 15, block: 'p',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p³', electronegativity: 2.18, density: 5.776,
    meltingPoint: 817, boilingPoint: 614,
    discoveredBy: 'Albertus Magnus', yearDiscovered: 1250,
    funFact: '砷被称为"继承之毒"，因为历史上被用于暗杀。但砷化镓是重要的半导体材料！',
    row: 4, col: 15,
  },
  {
    number: 34, symbol: 'Se', name: '硒', nameEn: 'Selenium',
    category: 'nonmetal', atomicMass: 78.971, period: 4, group: 16, block: 'p',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴', electronegativity: 2.55, density: 4.809,
    meltingPoint: 221, boilingPoint: 685,
    discoveredBy: 'Jöns Jacob Berzelius', yearDiscovered: 1817,
    funFact: '硒是人体必需的微量元素，巴西坚果含硒特别多。名字来源于月亮女神 Selene。',
    row: 4, col: 16,
  },
  {
    number: 35, symbol: 'Br', name: '溴', nameEn: 'Bromine',
    category: 'halogen', atomicMass: 79.904, period: 4, group: 17, block: 'p',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵', electronegativity: 2.96, density: 3.122,
    meltingPoint: -7.2, boilingPoint: 58.8,
    discoveredBy: 'Antoine Jérôme Balard', yearDiscovered: 1826,
    funFact: '溴是常温下唯一呈液态的非金属元素，有刺鼻的恶臭！名字来自希腊语"臭气"。',
    row: 4, col: 17,
  },
  {
    number: 36, symbol: 'Kr', name: '氪', nameEn: 'Krypton',
    category: 'noble-gas', atomicMass: 83.798, period: 4, group: 18, block: 'p',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶', density: 0.003733,
    meltingPoint: -157.36, boilingPoint: -153.22,
    discoveredBy: 'William Ramsay', yearDiscovered: 1898,
    funFact: '氪星（Krypton）是超人的故乡！实际上氪气用于高性能照明和激光。',
    row: 4, col: 18,
  },
  {
    number: 37, symbol: 'Rb', name: '铷', nameEn: 'Rubidium',
    category: 'alkali-metal', atomicMass: 85.468, period: 5, group: 1, block: 's',
    electronConfig: '[Kr] 5s¹', electronegativity: 0.82, density: 1.532,
    meltingPoint: 39.31, boilingPoint: 688,
    discoveredBy: 'Robert Bunsen', yearDiscovered: 1861,
    funFact: '铷遇水会剧烈爆炸！它的名字来自拉丁语"深红色"，因为光谱线是红色的。',
    row: 5, col: 1,
  },
  {
    number: 38, symbol: 'Sr', name: '锶', nameEn: 'Strontium',
    category: 'alkaline-earth', atomicMass: 87.62, period: 5, group: 2, block: 's',
    electronConfig: '[Kr] 5s²', electronegativity: 0.95, density: 2.64,
    meltingPoint: 777, boilingPoint: 1382,
    discoveredBy: 'William Cruickshank', yearDiscovered: 1790,
    funFact: '锶是烟花中红色的来源！锶-90 是核裂变产物，需要小心处理。',
    row: 5, col: 2,
  },
  {
    number: 39, symbol: 'Y', name: '钇', nameEn: 'Yttrium',
    category: 'transition-metal', atomicMass: 88.906, period: 5, group: 3, block: 'd',
    electronConfig: '[Kr] 4d¹ 5s²', electronegativity: 1.22, density: 4.469,
    meltingPoint: 1526, boilingPoint: 3345,
    discoveredBy: 'Johan Gadolin', yearDiscovered: 1794,
    funFact: '钇是第一个被发现的稀土元素，以瑞典村庄 Ytterby 命名，有 4 个元素以此村命名！',
    row: 5, col: 3,
  },
  {
    number: 40, symbol: 'Zr', name: '锆', nameEn: 'Zirconium',
    category: 'transition-metal', atomicMass: 91.224, period: 5, group: 4, block: 'd',
    electronConfig: '[Kr] 4d² 5s²', electronegativity: 1.33, density: 6.506,
    meltingPoint: 1855, boilingPoint: 4409,
    discoveredBy: 'Martin Heinrich Klaproth', yearDiscovered: 1789,
    funFact: '锆宝石（立方氧化锆）是钻石的仿品，肉眼几乎无法分辨！核反应棒也用锆。',
    row: 5, col: 4,
  },
  {
    number: 41, symbol: 'Nb', name: '铌', nameEn: 'Niobium',
    category: 'transition-metal', atomicMass: 92.906, period: 5, group: 5, block: 'd',
    electronConfig: '[Kr] 4d⁴ 5s¹', electronegativity: 1.6, density: 8.57,
    meltingPoint: 2477, boilingPoint: 4744,
    discoveredBy: 'Charles Hatchett', yearDiscovered: 1801,
    funFact: '铌用于超导磁体，MRI 机器中的超导线圈就含有铌！以希腊神话人物 Niobe 命名。',
    row: 5, col: 5,
  },
  {
    number: 42, symbol: 'Mo', name: '钼', nameEn: 'Molybdenum',
    category: 'transition-metal', atomicMass: 95.95, period: 5, group: 6, block: 'd',
    electronConfig: '[Kr] 4d⁵ 5s¹', electronegativity: 2.16, density: 10.22,
    meltingPoint: 2623, boilingPoint: 4639,
    discoveredBy: 'Carl Wilhelm Scheele', yearDiscovered: 1778,
    funFact: '钼是植物和某些酶必需的元素。名字来自希腊语"铅"，因为常和铅矿共生。',
    row: 5, col: 6,
  },
  {
    number: 43, symbol: 'Tc', name: '锝', nameEn: 'Technetium',
    category: 'transition-metal', atomicMass: 98, period: 5, group: 7, block: 'd',
    electronConfig: '[Kr] 4d⁵ 5s²', electronegativity: 1.9, density: 11.5,
    meltingPoint: 2157, boilingPoint: 4265,
    discoveredBy: 'Emilio Segrè', yearDiscovered: 1937,
    funFact: '锝是第一个人工合成的元素！名字来自希腊语"人造的"，用于医学成像。',
    row: 5, col: 7,
  },
  {
    number: 44, symbol: 'Ru', name: '钌', nameEn: 'Ruthenium',
    category: 'transition-metal', atomicMass: 101.07, period: 5, group: 8, block: 'd',
    electronConfig: '[Kr] 4d⁷ 5s¹', electronegativity: 2.2, density: 12.37,
    meltingPoint: 2334, boilingPoint: 4150,
    discoveredBy: 'Karl Ernst Claus', yearDiscovered: 1844,
    funFact: '钌以俄罗斯命名（Ruthenia），是铂族金属中最便宜的一种。',
    row: 5, col: 8,
  },
  {
    number: 45, symbol: 'Rh', name: '铑', nameEn: 'Rhodium',
    category: 'transition-metal', atomicMass: 102.906, period: 5, group: 9, block: 'd',
    electronConfig: '[Kr] 4d⁸ 5s¹', electronegativity: 2.28, density: 12.41,
    meltingPoint: 1964, boilingPoint: 3695,
    discoveredBy: 'William Hyde Wollaston', yearDiscovered: 1803,
    funFact: '铑是世界上最昂贵的金属之一！汽车催化转化器中的铑可以减少有害排放。',
    row: 5, col: 9,
  },
  {
    number: 46, symbol: 'Pd', name: '钯', nameEn: 'Palladium',
    category: 'transition-metal', atomicMass: 106.42, period: 5, group: 10, block: 'd',
    electronConfig: '[Kr] 4d¹⁰', electronegativity: 2.20, density: 12.02,
    meltingPoint: 1554.9, boilingPoint: 2963,
    discoveredBy: 'William Hyde Wollaston', yearDiscovered: 1803,
    funFact: '钯能吸收自身体积 900 倍的氢气！以小行星 Pallas 命名。',
    row: 5, col: 10,
  },
  {
    number: 47, symbol: 'Ag', name: '银', nameEn: 'Silver',
    category: 'transition-metal', atomicMass: 107.868, period: 5, group: 11, block: 'd',
    electronConfig: '[Kr] 4d¹⁰ 5s¹', electronegativity: 1.93, density: 10.501,
    meltingPoint: 961.78, boilingPoint: 2162,
    funFact: '银是导电性和导热性最好的金属！银器接触鸡蛋会变黑，因为硫化银。',
    row: 5, col: 11,
  },
  {
    number: 48, symbol: 'Cd', name: '镉', nameEn: 'Cadmium',
    category: 'transition-metal', atomicMass: 112.414, period: 5, group: 12, block: 'd',
    electronConfig: '[Kr] 4d¹⁰ 5s²', electronegativity: 1.69, density: 8.69,
    meltingPoint: 321.07, boilingPoint: 767,
    discoveredBy: 'Karl Samuel Leberecht Hermann', yearDiscovered: 1817,
    funFact: '镉的化合物颜色鲜艳：黄色、红色、橙色。但镉有毒，现在已限制使用。',
    row: 5, col: 12,
  },
  {
    number: 49, symbol: 'In', name: '铟', nameEn: 'Indium',
    category: 'post-transition', atomicMass: 114.818, period: 5, group: 13, block: 'p',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹', electronegativity: 1.78, density: 7.31,
    meltingPoint: 156.6, boilingPoint: 2072,
    discoveredBy: 'Ferdinand Reich', yearDiscovered: 1863,
    funFact: '铟弯曲时会发出"锡哭"般的叫声！触摸屏的透明导电层就含铟锡氧化物。',
    row: 5, col: 13,
  },
  {
    number: 50, symbol: 'Sn', name: '锡', nameEn: 'Tin',
    category: 'post-transition', atomicMass: 118.710, period: 5, group: 14, block: 'p',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p²', electronegativity: 1.96, density: 7.287,
    meltingPoint: 231.93, boilingPoint: 2602,
    funFact: '锡是人类最早使用的金属之一！"罐头"就是镀锡的铁。锡在低温会变成灰色粉末。',
    row: 5, col: 14,
  },
  {
    number: 51, symbol: 'Sb', name: '锑', nameEn: 'Antimony',
    category: 'metalloid', atomicMass: 121.760, period: 5, group: 15, block: 'p',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p³', electronegativity: 2.05, density: 6.685,
    meltingPoint: 630.63, boilingPoint: 1587,
    discoveredBy: 'Ancient', yearDiscovered: -3000,
    funFact: '锑在古代就被用作化妆品（眼影）！阻燃剂中也含有锑。',
    row: 5, col: 15,
  },
  {
    number: 52, symbol: 'Te', name: '碲', nameEn: 'Tellurium',
    category: 'metalloid', atomicMass: 127.60, period: 5, group: 16, block: 'p',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴', electronegativity: 2.1, density: 6.232,
    meltingPoint: 449.51, boilingPoint: 988,
    discoveredBy: 'Franz-Joseph Müller von Reichenstein', yearDiscovered: 1782,
    funFact: '碲以地球女神 Tellus 命名。吃了碲食物后，汗液和呼吸会有大蒜味！',
    row: 5, col: 16,
  },
  {
    number: 53, symbol: 'I', name: '碘', nameEn: 'Iodine',
    category: 'halogen', atomicMass: 126.904, period: 5, group: 17, block: 'p',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵', electronegativity: 2.66, density: 4.93,
    meltingPoint: 113.7, boilingPoint: 184.3,
    discoveredBy: 'Bernard Courtois', yearDiscovered: 1811,
    funFact: '碘加热会升华成紫色气体！缺碘会导致甲状腺肿大（大脖子病）。',
    row: 5, col: 17,
  },
  {
    number: 54, symbol: 'Xe', name: '氙', nameEn: 'Xenon',
    category: 'noble-gas', atomicMass: 131.293, period: 5, group: 18, block: 'p',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶', density: 0.005887,
    meltingPoint: -111.75, boilingPoint: -108.1,
    discoveredBy: 'William Ramsay', yearDiscovered: 1898,
    funFact: '氙闪光灯发出的光非常接近太阳光！氙气曾被认为完全惰性，但后来合成了氙化合物。',
    row: 5, col: 18,
  },
  {
    number: 55, symbol: 'Cs', name: '铯', nameEn: 'Caesium',
    category: 'alkali-metal', atomicMass: 132.905, period: 6, group: 1, block: 's',
    electronConfig: '[Xe] 6s¹', electronegativity: 0.79, density: 1.873,
    meltingPoint: 28.44, boilingPoint: 671,
    discoveredBy: 'Robert Bunsen', yearDiscovered: 1860,
    funFact: '铯是秒的定义基准！铯原子钟每 300 万年才误差 1 秒。',
    row: 6, col: 1,
  },
  {
    number: 56, symbol: 'Ba', name: '钡', nameEn: 'Barium',
    category: 'alkaline-earth', atomicMass: 137.327, period: 6, group: 2, block: 's',
    electronConfig: '[Xe] 6s²', electronegativity: 0.89, density: 3.594,
    meltingPoint: 727, boilingPoint: 1845,
    discoveredBy: 'Carl Wilhelm Scheele', yearDiscovered: 1772,
    funFact: '钡餐（硫酸钡）是 X 光检查消化道的造影剂！可溶性钡盐有毒。',
    row: 6, col: 2,
  },
  {
    number: 57, symbol: 'La', name: '镧', nameEn: 'Lanthanum',
    category: 'lanthanide', atomicMass: 138.905, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 5d¹ 6s²', electronegativity: 1.1, density: 6.145,
    meltingPoint: 920, boilingPoint: 3464,
    discoveredBy: 'Carl Gustaf Mosander', yearDiscovered: 1839,
    funFact: '镧是镧系元素的第一个，名字来自希腊语"隐藏"。混合动力车电池含镧。',
    row: 9, col: 3,
  },
  {
    number: 58, symbol: 'Ce', name: '铈', nameEn: 'Cerium',
    category: 'lanthanide', atomicMass: 140.116, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f¹ 5d¹ 6s²', electronegativity: 1.12, density: 6.77,
    meltingPoint: 795, boilingPoint: 3443,
    discoveredBy: 'Jöns Jacob Berzelius', yearDiscovered: 1803,
    funFact: '铈是含量最丰富的稀土元素，打火机的火石就含铈！以小行星谷神星命名。',
    row: 9, col: 4,
  },
  {
    number: 59, symbol: 'Pr', name: '镨', nameEn: 'Praseodymium',
    category: 'lanthanide', atomicMass: 140.908, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f³ 6s²', electronegativity: 1.13, density: 7.77,
    meltingPoint: 935, boilingPoint: 3520,
    discoveredBy: 'Carl Auer von Welsbach', yearDiscovered: 1885,
    funFact: '镨和钕的混合物叫"黄绿"，用于制造绿色玻璃。名字意为"绿色的双胞胎"。',
    row: 9, col: 5,
  },
  {
    number: 60, symbol: 'Nd', name: '钕', nameEn: 'Neodymium',
    category: 'lanthanide', atomicMass: 144.242, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f⁴ 6s²', electronegativity: 1.14, density: 7.007,
    meltingPoint: 1024, boilingPoint: 3074,
    discoveredBy: 'Carl Auer von Welsbach', yearDiscovered: 1885,
    funFact: '钕磁铁是最强的永磁体，比普通磁铁强 10 倍以上！耳机、硬盘都用它。',
    row: 9, col: 6,
  },
  {
    number: 61, symbol: 'Pm', name: '钷', nameEn: 'Promethium',
    category: 'lanthanide', atomicMass: 145, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f⁵ 6s²', electronegativity: 1.13, density: 7.26,
    meltingPoint: 1042, boilingPoint: 3000,
    discoveredBy: 'Chien Shiung Wu', yearDiscovered: 1945,
    funFact: '钷是唯一没有稳定同位素的稀土元素！用于夜光涂料和核电池。',
    row: 9, col: 7,
  },
  {
    number: 62, symbol: 'Sm', name: '钐', nameEn: 'Samarium',
    category: 'lanthanide', atomicMass: 150.36, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f⁶ 6s²', electronegativity: 1.17, density: 7.52,
    meltingPoint: 1072, boilingPoint: 1794,
    discoveredBy: 'Lecoq de Boisbaudran', yearDiscovered: 1879,
    funFact: '钐钴磁铁耐高温，用于导弹和航天器！以俄罗斯矿物学家 Vasili Samarski 命名。',
    row: 9, col: 8,
  },
  {
    number: 63, symbol: 'Eu', name: '铕', nameEn: 'Europium',
    category: 'lanthanide', atomicMass: 151.964, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f⁷ 6s²', electronegativity: 1.2, density: 5.243,
    meltingPoint: 826, boilingPoint: 1529,
    discoveredBy: 'Eugène-Anatole Demarçay', yearDiscovered: 1901,
    funFact: '铕是欧元纸币防伪标记中的荧光物质！也是红色荧光粉的成分。',
    row: 9, col: 9,
  },
  {
    number: 64, symbol: 'Gd', name: '钆', nameEn: 'Gadolinium',
    category: 'lanthanide', atomicMass: 157.25, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f⁷ 5d¹ 6s²', electronegativity: 1.2, density: 7.895,
    meltingPoint: 1312, boilingPoint: 3273,
    discoveredBy: 'Jean Charles Galissard de Marignac', yearDiscovered: 1880,
    funFact: '钆是 MRI 造影剂的主要成分！以芬兰化学家 Johan Gadolin 命名。',
    row: 9, col: 10,
  },
  {
    number: 65, symbol: 'Tb', name: '铽', nameEn: 'Terbium',
    category: 'lanthanide', atomicMass: 158.925, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f⁹ 6s²', electronegativity: 1.2, density: 8.229,
    meltingPoint: 1356, boilingPoint: 3230,
    discoveredBy: 'Carl Gustaf Mosander', yearDiscovered: 1843,
    funFact: '铽的化合物在紫外线下会发出绿色荧光！以瑞典村庄 Ytterby 命名。',
    row: 9, col: 11,
  },
  {
    number: 66, symbol: 'Dy', name: '镝', nameEn: 'Dysprosium',
    category: 'lanthanide', atomicMass: 162.500, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f¹⁰ 6s²', electronegativity: 1.22, density: 8.55,
    meltingPoint: 1407, boilingPoint: 2567,
    discoveredBy: 'Lecoq de Boisbaudran', yearDiscovered: 1886,
    funFact: '镝名字来自希腊语"难以获得"。添加镝可以提高钕磁铁的耐热性。',
    row: 9, col: 12,
  },
  {
    number: 67, symbol: 'Ho', name: '钬', nameEn: 'Holmium',
    category: 'lanthanide', atomicMass: 164.930, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f¹¹ 6s²', electronegativity: 1.23, density: 8.795,
    meltingPoint: 1461, boilingPoint: 2720,
    discoveredBy: 'Marc Delafontaine', yearDiscovered: 1878,
    funFact: '钬有所有元素中最高的磁矩！以斯德哥尔摩（Holmia）命名。',
    row: 9, col: 13,
  },
  {
    number: 68, symbol: 'Er', name: '铒', nameEn: 'Erbium',
    category: 'lanthanide', atomicMass: 167.259, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f¹² 6s²', electronegativity: 1.24, density: 9.066,
    meltingPoint: 1529, boilingPoint: 2868,
    discoveredBy: 'Carl Gustaf Mosander', yearDiscovered: 1842,
    funFact: '铒是光纤通信中常用的掺铒光纤放大器的核心！以 Ytterby 村命名。',
    row: 9, col: 14,
  },
  {
    number: 69, symbol: 'Tm', name: '铥', nameEn: 'Thulium',
    category: 'lanthanide', atomicMass: 168.934, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f¹³ 6s²', electronegativity: 1.25, density: 9.321,
    meltingPoint: 1545, boilingPoint: 1950,
    discoveredBy: 'Per Teodor Cleve', yearDiscovered: 1879,
    funFact: '铥是最稀有的稀土元素之一，以古代北欧名称 Thule 命名。',
    row: 9, col: 15,
  },
  {
    number: 70, symbol: 'Yb', name: '镱', nameEn: 'Ytterbium',
    category: 'lanthanide', atomicMass: 173.045, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f¹⁴ 6s²', electronegativity: 1.1, density: 6.965,
    meltingPoint: 824, boilingPoint: 1196,
    discoveredBy: 'Jean Charles Galissard de Marignac', yearDiscovered: 1878,
    funFact: '镱原子钟比铯原子钟更精确！以 Ytterby 村命名（第四个以此村命名的元素）。',
    row: 9, col: 16,
  },
  {
    number: 71, symbol: 'Lu', name: '镥', nameEn: 'Lutetium',
    category: 'lanthanide', atomicMass: 174.967, period: 6, group: 3, block: 'f',
    electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²', electronegativity: 1.27, density: 9.84,
    meltingPoint: 1663, boilingPoint: 3402,
    discoveredBy: 'Georges Urbain', yearDiscovered: 1907,
    funFact: '镥是镧系最后一个元素，以巴黎的古名 Lutetia 命名。',
    row: 9, col: 17,
  },
  {
    number: 72, symbol: 'Hf', name: '铪', nameEn: 'Hafnium',
    category: 'transition-metal', atomicMass: 178.49, period: 6, group: 4, block: 'd',
    electronConfig: '[Xe] 4f¹⁴ 5d² 6s²', electronegativity: 1.3, density: 13.31,
    meltingPoint: 2233, boilingPoint: 4603,
    discoveredBy: 'Dirk Coster', yearDiscovered: 1923,
    funFact: '铪以哥本哈根的拉丁名 Hafnia 命名。核反应堆控制棒用铪，因为它能吸收中子。',
    row: 6, col: 4,
  },
  {
    number: 73, symbol: 'Ta', name: '钽', nameEn: 'Tantalum',
    category: 'transition-metal', atomicMass: 180.948, period: 6, group: 5, block: 'd',
    electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²', electronegativity: 1.5, density: 16.654,
    meltingPoint: 3017, boilingPoint: 5458,
    discoveredBy: 'Anders Gustaf Ekeberg', yearDiscovered: 1802,
    funFact: '钽耐酸性极强，几乎不被任何酸腐蚀！手机和电脑电容器含有钽。以希腊神话 Tantalus 命名。',
    row: 6, col: 5,
  },
  {
    number: 74, symbol: 'W', name: '钨', nameEn: 'Tungsten',
    category: 'transition-metal', atomicMass: 183.84, period: 6, group: 6, block: 'd',
    electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²', electronegativity: 2.36, density: 19.25,
    meltingPoint: 3422, boilingPoint: 5555,
    discoveredBy: 'Carl Wilhelm Scheele', yearDiscovered: 1781,
    funFact: '钨的熔点是所有金属中最高的！白炽灯泡的灯丝就是钨丝。W 来自德语 Wolfram。',
    row: 6, col: 6,
  },
  {
    number: 75, symbol: 'Re', name: '铼', nameEn: 'Rhenium',
    category: 'transition-metal', atomicMass: 186.207, period: 6, group: 7, block: 'd',
    electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²', electronegativity: 1.9, density: 21.02,
    meltingPoint: 3186, boilingPoint: 5596,
    discoveredBy: 'Masataka Ogawa', yearDiscovered: 1908,
    funFact: '铼是最后一个被发现的稳定元素，以莱茵河命名。喷气发动机的高温合金含铼。',
    row: 6, col: 7,
  },
  {
    number: 76, symbol: 'Os', name: '锇', nameEn: 'Osmium',
    category: 'transition-metal', atomicMass: 190.23, period: 6, group: 8, block: 'd',
    electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²', electronegativity: 2.2, density: 22.587,
    meltingPoint: 3033, boilingPoint: 5012,
    discoveredBy: 'Smithson Tennant', yearDiscovered: 1803,
    funFact: '锇是密度最大的元素！名字来自希腊语"气味"，因为氧化锇有刺鼻臭味。',
    row: 6, col: 8,
  },
  {
    number: 77, symbol: 'Ir', name: '铱', nameEn: 'Iridium',
    category: 'transition-metal', atomicMass: 192.217, period: 6, group: 9, block: 'd',
    electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²', electronegativity: 2.2, density: 22.56,
    meltingPoint: 2446, boilingPoint: 4428,
    discoveredBy: 'Smithson Tennant', yearDiscovered: 1803,
    funFact: '铱在地壳中很稀少，但恐龙灭绝的地层有大量铱，可能是小行星撞击带来的！',
    row: 6, col: 9,
  },
  {
    number: 78, symbol: 'Pt', name: '铂', nameEn: 'Platinum',
    category: 'transition-metal', atomicMass: 195.084, period: 6, group: 10, block: 'd',
    electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹', electronegativity: 2.28, density: 21.46,
    meltingPoint: 1768.3, boilingPoint: 3825,
    discoveredBy: 'Antonio de Ulloa', yearDiscovered: 1735,
    funFact: '铂金比黄金稀有 30 倍！催化转化器、首饰和化疗药物都用到铂。',
    row: 6, col: 10,
  },
  {
    number: 79, symbol: 'Au', name: '金', nameEn: 'Gold',
    category: 'transition-metal', atomicMass: 196.967, period: 6, group: 11, block: 'd',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', electronegativity: 2.54, density: 19.282,
    meltingPoint: 1064.18, boilingPoint: 2856,
    funFact: '金是唯一金黄色的金属！一盎司金可以拉成 80 公里长的线。地球上的金来自陨石。',
    row: 6, col: 11,
  },
  {
    number: 80, symbol: 'Hg', name: '汞', nameEn: 'Mercury',
    category: 'transition-metal', atomicMass: 200.592, period: 6, group: 12, block: 'd',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²', electronegativity: 2.0, density: 13.5336,
    meltingPoint: -38.83, boilingPoint: 356.73,
    discoveredBy: 'Ancient', yearDiscovered: -1500,
    funFact: '汞是常温下唯一呈液态的金属！水银温度计就是利用这个特性。以行星 Mercury 命名。',
    row: 6, col: 12,
  },
  {
    number: 81, symbol: 'Tl', name: '铊', nameEn: 'Thallium',
    category: 'post-transition', atomicMass: 204.38, period: 6, group: 13, block: 'p',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', electronegativity: 1.62, density: 11.85,
    meltingPoint: 304, boilingPoint: 1473,
    discoveredBy: 'William Crookes', yearDiscovered: 1861,
    funFact: '铊的光谱线是嫩绿色，名字来自希腊语"嫩枝"。铊有毒，需要特别小心。',
    row: 6, col: 13,
  },
  {
    number: 82, symbol: 'Pb', name: '铅', nameEn: 'Lead',
    category: 'post-transition', atomicMass: 207.2, period: 6, group: 14, block: 'p',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', electronegativity: 2.33, density: 11.342,
    meltingPoint: 327.46, boilingPoint: 1749,
    funFact: '罗马人用铅管引水，"铅"的符号 Pb 来自拉丁语 Plumbum，水管工(plumber)就是这么来的！',
    row: 6, col: 14,
  },
  {
    number: 83, symbol: 'Bi', name: '铋', nameEn: 'Bismuth',
    category: 'post-transition', atomicMass: 208.980, period: 6, group: 15, block: 'p',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', electronegativity: 2.02, density: 9.807,
    meltingPoint: 271.4, boilingPoint: 1564,
    discoveredBy: 'Claude François Geoffroy', yearDiscovered: 1753,
    funFact: '铋晶体有彩虹般的阶梯状结构，非常漂亮！胃药"次水杨酸铋"含铋。',
    row: 6, col: 15,
  },
  {
    number: 84, symbol: 'Po', name: '钋', nameEn: 'Polonium',
    category: 'post-transition', atomicMass: 209, period: 6, group: 16, block: 'p',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', electronegativity: 2.0, density: 9.32,
    meltingPoint: 254, boilingPoint: 962,
    discoveredBy: 'Pierre Curie', yearDiscovered: 1898,
    funFact: '钋以居里夫人的祖国波兰命名！它非常放射性，曾被用于暗杀。',
    row: 6, col: 16,
  },
  {
    number: 85, symbol: 'At', name: '砹', nameEn: 'Astatine',
    category: 'halogen', atomicMass: 210, period: 6, group: 17, block: 'p',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', electronegativity: 2.2, density: 7,
    meltingPoint: 302, boilingPoint: 337,
    discoveredBy: 'Dale R. Corson', yearDiscovered: 1940,
    funFact: '砹是地壳中最稀有的自然元素，整个地壳同时存在的砹不到 1 克！名字意为"不稳定"。',
    row: 6, col: 17,
  },
  {
    number: 86, symbol: 'Rn', name: '氡', nameEn: 'Radon',
    category: 'noble-gas', atomicMass: 222, period: 6, group: 18, block: 'p',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', density: 0.00973,
    meltingPoint: -71, boilingPoint: -61.7,
    discoveredBy: 'Friedrich Ernst Dorn', yearDiscovered: 1900,
    funFact: '氡是放射性气体，会从地下渗入地下室。以镭（Radium）派生命名。',
    row: 6, col: 18,
  },
  {
    number: 87, symbol: 'Fr', name: '钫', nameEn: 'Francium',
    category: 'alkali-metal', atomicMass: 223, period: 7, group: 1, block: 's',
    electronConfig: '[Rn] 7s¹', electronegativity: 0.7, density: 1.87,
    meltingPoint: 27, boilingPoint: 677,
    discoveredBy: 'Marguerite Perey', yearDiscovered: 1939,
    funFact: '钫是最不稳定的天然元素，半衰期最长仅 22 分钟！整个地壳同时存在的钫不到 30 克。',
    row: 7, col: 1,
  },
  {
    number: 88, symbol: 'Ra', name: '镭', nameEn: 'Radium',
    category: 'alkaline-earth', atomicMass: 226, period: 7, group: 2, block: 's',
    electronConfig: '[Rn] 7s²', electronegativity: 0.9, density: 5.5,
    meltingPoint: 700, boilingPoint: 1737,
    discoveredBy: 'Pierre Curie', yearDiscovered: 1898,
    funFact: '镭会发光！居里夫人发现镭时，曾把装有镭的瓶子放在床头。镭曾被加入牙膏和化妆品。',
    row: 7, col: 2,
  },
  {
    number: 89, symbol: 'Ac', name: '锕', nameEn: 'Actinium',
    category: 'actinide', atomicMass: 227, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 6d¹ 7s²', electronegativity: 1.1, density: 10.07,
    meltingPoint: 1050, boilingPoint: 3198,
    discoveredBy: 'André-Louis Debierne', yearDiscovered: 1899,
    funFact: '锕在黑暗中会发出蓝色的光！名字来自希腊语"射线"，锕系元素因此得名。',
    row: 10, col: 3,
  },
  {
    number: 90, symbol: 'Th', name: '钍', nameEn: 'Thorium',
    category: 'actinide', atomicMass: 232.038, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 6d² 7s²', electronegativity: 1.3, density: 11.72,
    meltingPoint: 1750, boilingPoint: 4788,
    discoveredBy: 'Jöns Jacob Berzelius', yearDiscovered: 1829,
    funFact: '钍是核能的潜在燃料，储量比铀多 3-4 倍！以北欧雷神 Thor 命名。',
    row: 10, col: 4,
  },
  {
    number: 91, symbol: 'Pa', name: '镤', nameEn: 'Protactinium',
    category: 'actinide', atomicMass: 231.036, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f² 6d¹ 7s²', electronegativity: 1.5, density: 15.37,
    meltingPoint: 1572, boilingPoint: 4027,
    discoveredBy: 'Kasimir Fajans', yearDiscovered: 1913,
    funFact: '镤是锕系中最稀有的元素，地壳含量比镭还少！名字意为"锕之父"。',
    row: 10, col: 5,
  },
  {
    number: 92, symbol: 'U', name: '铀', nameEn: 'Uranium',
    category: 'actinide', atomicMass: 238.029, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f³ 6d¹ 7s²', electronegativity: 1.38, density: 18.95,
    meltingPoint: 1135, boilingPoint: 4131,
    discoveredBy: 'Martin Heinrich Klaproth', yearDiscovered: 1789,
    funFact: '铀是核能和核武器的燃料。1 公斤铀裂变释放的能量相当于 2500 吨煤！以天王星命名。',
    row: 10, col: 6,
  },
  {
    number: 93, symbol: 'Np', name: '镎', nameEn: 'Neptunium',
    category: 'actinide', atomicMass: 237, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f⁴ 6d¹ 7s²', electronegativity: 1.36, density: 20.45,
    meltingPoint: 644, boilingPoint: 3902,
    discoveredBy: 'Edwin McMillan', yearDiscovered: 1940,
    funFact: '镎是第一个超铀元素，以海王星命名（继铀-天王星之后）。',
    row: 10, col: 7,
  },
  {
    number: 94, symbol: 'Pu', name: '钚', nameEn: 'Plutonium',
    category: 'actinide', atomicMass: 244, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f⁶ 7s²', electronegativity: 1.28, density: 19.84,
    meltingPoint: 640, boilingPoint: 3228,
    discoveredBy: 'Glenn T. Seaborg', yearDiscovered: 1940,
    funFact: '钚是核武器的重要材料，也是深空探测器的能源。以冥王星命名。',
    row: 10, col: 8,
  },
  {
    number: 95, symbol: 'Am', name: '镅', nameEn: 'Americium',
    category: 'actinide', atomicMass: 243, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f⁷ 7s²', electronegativity: 1.3, density: 13.69,
    meltingPoint: 1176, boilingPoint: 2011,
    discoveredBy: 'Glenn T. Seaborg', yearDiscovered: 1944,
    funFact: '家用烟雾报警器中含有镅-241！以美洲命名（继铕-欧洲之后）。',
    row: 10, col: 9,
  },
  {
    number: 96, symbol: 'Cm', name: '锔', nameEn: 'Curium',
    category: 'actinide', atomicMass: 247, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f⁷ 6d¹ 7s²', electronegativity: 1.3, density: 13.51,
    meltingPoint: 1340, boilingPoint: 3110,
    discoveredBy: 'Glenn T. Seaborg', yearDiscovered: 1944,
    funFact: '锔以居里夫妇命名，是深空探测器的重要能源。',
    row: 10, col: 10,
  },
  {
    number: 97, symbol: 'Bk', name: '锫', nameEn: 'Berkelium',
    category: 'actinide', atomicMass: 247, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f⁹ 7s²', electronegativity: 1.3, density: 14.79,
    meltingPoint: 986, boilingPoint: 2627,
    discoveredBy: 'Glenn T. Seaborg', yearDiscovered: 1949,
    funFact: '锫以加州伯克利命名，是合成锿和镄的原料。',
    row: 10, col: 11,
  },
  {
    number: 98, symbol: 'Cf', name: '锎', nameEn: 'Californium',
    category: 'actinide', atomicMass: 251, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f¹⁰ 7s²', electronegativity: 1.3, density: 15.1,
    meltingPoint: 900, boilingPoint: 1470,
    discoveredBy: 'Glenn T. Seaborg', yearDiscovered: 1950,
    funFact: '锎是最强的便携中子源，用于检测金矿和治疗癌症。以加州命名。',
    row: 10, col: 12,
  },
  {
    number: 99, symbol: 'Es', name: '锿', nameEn: 'Einsteinium',
    category: 'actinide', atomicMass: 252, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f¹¹ 7s²', electronegativity: 1.3, density: 8.84,
    meltingPoint: 860, boilingPoint: 996,
    discoveredBy: 'Albert Ghiorso', yearDiscovered: 1952,
    funFact: '锿在氢弹爆炸残骸中首次发现！以爱因斯坦命名。',
    row: 10, col: 13,
  },
  {
    number: 100, symbol: 'Fm', name: '镄', nameEn: 'Fermium',
    category: 'actinide', atomicMass: 257, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f¹² 7s²', electronegativity: 1.3, density: 9.7,
    meltingPoint: 1527, boilingPoint: 0,
    discoveredBy: 'Albert Ghiorso', yearDiscovered: 1952,
    funFact: '镄也来自氢弹残骸，以物理学家费米命名。只能微量合成。',
    row: 10, col: 14,
  },
  {
    number: 101, symbol: 'Md', name: '钔', nameEn: 'Mendelevium',
    category: 'actinide', atomicMass: 258, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f¹³ 7s²', electronegativity: 1.3, density: 10.3,
    meltingPoint: 827, boilingPoint: 0,
    discoveredBy: 'Albert Ghiorso', yearDiscovered: 1955,
    funFact: '钔以门捷列夫命名，纪念他发明了元素周期表。首次只合成了 17 个原子！',
    row: 10, col: 15,
  },
  {
    number: 102, symbol: 'No', name: '锘', nameEn: 'Nobelium',
    category: 'actinide', atomicMass: 259, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f¹⁴ 7s²', electronegativity: 1.3, density: 9.9,
    meltingPoint: 827, boilingPoint: 0,
    discoveredBy: 'Albert Ghiorso', yearDiscovered: 1966,
    funFact: '锘以诺贝尔奖创始人诺贝尔命名。',
    row: 10, col: 16,
  },
  {
    number: 103, symbol: 'Lr', name: '铹', nameEn: 'Lawrencium',
    category: 'actinide', atomicMass: 266, period: 7, group: 3, block: 'f',
    electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹', electronegativity: 1.3, density: 15.6,
    meltingPoint: 1627, boilingPoint: 0,
    discoveredBy: 'Albert Ghiorso', yearDiscovered: 1961,
    funFact: '铹以回旋加速器发明者劳伦斯命名。',
    row: 10, col: 17,
  },
  {
    number: 104, symbol: 'Rf', name: '𬬻', nameEn: 'Rutherfordium',
    category: 'transition-metal', atomicMass: 267, period: 7, group: 4, block: 'd',
    electronConfig: '[Rn] 5f¹⁴ 6d² 7s²', density: 23.2,
    meltingPoint: 2100, boilingPoint: 5500,
    discoveredBy: 'Joint Institute for Nuclear Research', yearDiscovered: 1964,
    funFact: '第一个超锕系元素，以原子核物理之父卢瑟福命名。苏联和美国争夺命名权。',
    row: 7, col: 4,
  },
  {
    number: 105, symbol: 'Db', name: '𬭊', nameEn: 'Dubnium',
    category: 'transition-metal', atomicMass: 268, period: 7, group: 5, block: 'd',
    electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²', density: 29.3,
    meltingPoint: 0, boilingPoint: 0,
    discoveredBy: 'Joint Institute for Nuclear Research', yearDiscovered: 1968,
    funFact: '𬭊以俄罗斯杜布纳联合核研究所命名。',
    row: 7, col: 5,
  },
  {
    number: 106, symbol: 'Sg', name: '𬭳', nameEn: 'Seaborgium',
    category: 'transition-metal', atomicMass: 269, period: 7, group: 6, block: 'd',
    electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²', density: 35,
    meltingPoint: 0, boilingPoint: 0,
    discoveredBy: 'Albert Ghiorso', yearDiscovered: 1974,
    funFact: '𬭳是第一个以在世科学家命名的元素（西博格），曾引发争议。',
    row: 7, col: 6,
  },
  {
    number: 107, symbol: 'Bh', name: '𬭛', nameEn: 'Bohrium',
    category: 'transition-metal', atomicMass: 270, period: 7, group: 7, block: 'd',
    electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²', density: 37.1,
    meltingPoint: 0, boilingPoint: 0,
    discoveredBy: 'Peter Armbruster', yearDiscovered: 1981,
    funFact: '𬭛以玻尔模型的提出者尼尔斯·玻尔命名。',
    row: 7, col: 7,
  },
  {
    number: 108, symbol: 'Hs', name: '𬭶', nameEn: 'Hassium',
    category: 'transition-metal', atomicMass: 277, period: 7, group: 8, block: 'd',
    electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²', density: 40.7,
    meltingPoint: 0, boilingPoint: 0,
    discoveredBy: 'Peter Armbruster', yearDiscovered: 1984,
    funFact: '𬭶以德国达姆施塔特所在的黑森州命名。',
    row: 7, col: 8,
  },
  {
    number: 109, symbol: 'Mt', name: '鿏', nameEn: 'Meitnerium',
    category: 'transition-metal', atomicMass: 278, period: 7, group: 9, block: 'd',
    electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²', density: 37.4,
    meltingPoint: 0, boilingPoint: 0,
    discoveredBy: 'Peter Armbruster', yearDiscovered: 1982,
    funFact: '鿏以核裂变的发现者之一丽莎·迈特纳命名。',
    row: 7, col: 9,
  },
  {
    number: 110, symbol: 'Ds', name: '𫟼', nameEn: 'Darmstadtium',
    category: 'transition-metal', atomicMass: 281, period: 7, group: 10, block: 'd',
    electronConfig: '[Rn] 5f¹⁴ 6d⁸ 7s²', density: 34.8,
    meltingPoint: 0, boilingPoint: 0,
    discoveredBy: 'Peter Armbruster', yearDiscovered: 1994,
    funFact: '𫟼以发现地德国达姆施塔特命名。',
    row: 7, col: 10,
  },
  {
    number: 111, symbol: 'Rg', name: '𬬭', nameEn: 'Roentgenium',
    category: 'transition-metal', atomicMass: 282, period: 7, group: 11, block: 'd',
    electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s²', density: 28.7,
    meltingPoint: 0, boilingPoint: 0,
    discoveredBy: 'Peter Armbruster', yearDiscovered: 1994,
    funFact: '𬬭以 X 射线发现者伦琴命名。',
    row: 7, col: 11,
  },
  {
    number: 112, symbol: 'Cn', name: '鿔', nameEn: 'Copernicium',
    category: 'transition-metal', atomicMass: 285, period: 7, group: 12, block: 'd',
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', density: 23.7,
    meltingPoint: 0, boilingPoint: 357,
    discoveredBy: 'Sigurd Hofmann', yearDiscovered: 1996,
    funFact: '鿔以日心说提出者哥白尼命名。可能是液态金属！',
    row: 7, col: 12,
  },
  {
    number: 113, symbol: 'Nh', name: '鿭', nameEn: 'Nihonium',
    category: 'post-transition', atomicMass: 286, period: 7, group: 13, block: 'p',
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', density: 16,
    meltingPoint: 430, boilingPoint: 1100,
    discoveredBy: 'RIKEN', yearDiscovered: 2003,
    funFact: '鿭是第一个在亚洲（日本）发现的元素！名字来自日本"Nihon"。',
    row: 7, col: 13,
  },
  {
    number: 114, symbol: 'Fl', name: '𫓧', nameEn: 'Flerovium',
    category: 'post-transition', atomicMass: 289, period: 7, group: 14, block: 'p',
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', density: 14,
    meltingPoint: 67, boilingPoint: 147,
    discoveredBy: 'Joint Institute for Nuclear Research', yearDiscovered: 1998,
    funFact: '𫓧以苏联核物理研究所创始人弗廖罗夫命名。可能具有特殊性质。',
    row: 7, col: 14,
  },
  {
    number: 115, symbol: 'Mc', name: '镆', nameEn: 'Moscovium',
    category: 'post-transition', atomicMass: 290, period: 7, group: 15, block: 'p',
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', density: 13.5,
    meltingPoint: 400, boilingPoint: 1100,
    discoveredBy: 'Joint Institute for Nuclear Research', yearDiscovered: 2003,
    funFact: '镆以莫斯科州命名，杜布纳研究所位于此。',
    row: 7, col: 15,
  },
  {
    number: 116, symbol: 'Lv', name: '𫟷', nameEn: 'Livermorium',
    category: 'post-transition', atomicMass: 293, period: 7, group: 16, block: 'p',
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', density: 12.9,
    meltingPoint: 400, boilingPoint: 1080,
    discoveredBy: 'Joint Institute for Nuclear Research', yearDiscovered: 2000,
    funFact: '𫟷以美国劳伦斯利弗莫尔国家实验室命名。',
    row: 7, col: 16,
  },
  {
    number: 117, symbol: 'Ts', name: '鿬', nameEn: 'Tennessine',
    category: 'halogen', atomicMass: 294, period: 7, group: 17, block: 'p',
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', density: 7.2,
    meltingPoint: 450, boilingPoint: 610,
    discoveredBy: 'Joint Institute for Nuclear Research', yearDiscovered: 2010,
    funFact: '鿬以美国田纳西州命名，橡树岭国家实验室位于此。',
    row: 7, col: 17,
  },
  {
    number: 118, symbol: 'Og', name: '鿫', nameEn: 'Oganesson',
    category: 'noble-gas', atomicMass: 294, period: 7, group: 18, block: 'p',
    electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', density: 5.0,
    meltingPoint: 325, boilingPoint: 450,
    discoveredBy: 'Joint Institute for Nuclear Research', yearDiscovered: 2002,
    funFact: '鿫是目前周期表的最后一个元素，以核物理学家奥加涅相命名。',
    row: 7, col: 18,
  },
]
