// src/tools/registry.ts
// 工具注册表 — 每个工具模块在此注册

import { lazy } from 'react'
import type { ToolManifest } from '../types/tool'

// ============================================================
// 注册区 — 每新增一个工具，在这里加一行
// 格式：{ id, name, description, category, icon, keywords, path, component }
// ============================================================

const toolModules: ToolManifest[] = [
  // ── 常用工具 ──
  {
    id: 'qr-generator',
    name: '二维码生成',
    description: '文本/URL 生成二维码图片',
    category: 'common',
    icon: 'QrCode',
    keywords: ['二维码', 'qr', 'qrcode', 'url'],
    path: '/common/qr-generator',
    component: lazy(() => import('./common/QrGenerator')),
  },
  {
    id: 'password-generator',
    name: '随机密码生成',
    description: '自定义长度和字符集，生成强随机密码',
    category: 'common',
    icon: 'KeyRound',
    keywords: ['密码', 'password', '随机', 'random'],
    path: '/common/password-generator',
    component: lazy(() => import('./common/PasswordGenerator')),
  },
  {
    id: 'uuid-generator',
    name: 'UUID 生成器',
    description: '生成 UUID v1/v4/v5 唯一标识',
    category: 'common',
    icon: 'Fingerprint',
    keywords: ['uuid', 'guid', '唯一标识'],
    path: '/common/uuid-generator',
    component: lazy(() => import('./common/UuidGenerator')),
  },
  {
    id: 'unit-converter',
    name: '单位转换',
    description: '长度、重量、温度、面积等单位换算',
    category: 'common',
    icon: 'ArrowLeftRight',
    keywords: ['单位', '转换', '换算', 'unit'],
    path: '/common/unit-converter',
    component: lazy(() => import('./common/UnitConverter')),
  },
  {
    id: 'base-converter',
    name: '进制转换',
    description: '二进制、八进制、十进制、十六进制互转',
    category: 'common',
    icon: 'Binary',
    keywords: ['进制', '二进制', '十六进制', 'binary', 'hex'],
    path: '/common/base-converter',
    component: lazy(() => import('./common/BaseConverter')),
  },
  {
    id: 'countdown',
    name: '计时器 / 倒计时',
    description: '秒表计时和倒计时功能',
    category: 'common',
    icon: 'Timer',
    keywords: ['计时', '倒计时', '秒表', 'timer'],
    path: '/common/countdown',
    component: lazy(() => import('./common/Countdown')),
  },
  {
    id: 'interest-calculator',
    name: '利息计算器',
    description: '计算存款利息和贷款月供，支持定期存款和等额本息贷款',
    category: 'common',
    icon: 'Calculator',
    keywords: ['利息', '存款', '贷款', '月供', '利率', 'interest'],
    path: '/common/interest-calculator',
    component: lazy(() => import('./common/InterestCalculator')),
  },

  // ── 文本处理 ──
  {
    id: 'word-counter',
    name: '字数统计',
    description: '统计字符数、词数、行数、段落数',
    category: 'text',
    icon: 'AlignLeft',
    keywords: ['字数', '统计', '字符', 'word count'],
    path: '/text/word-counter',
    component: lazy(() => import('./text/WordCounter')),
  },
  {
    id: 'text-cleaner',
    name: '文本去空格换行',
    description: '去除多余空格、换行，支持多种清洗模式',
    category: 'text',
    icon: 'Eraser',
    keywords: ['去空格', '去换行', '清洗', 'clean'],
    path: '/text/text-cleaner',
    component: lazy(() => import('./text/TextCleaner')),
  },
  {
    id: 'case-converter',
    name: '大小写转换',
    description: 'UPPER/lower/CamelCase/snake_case 等格式互转',
    category: 'text',
    icon: 'CaseSensitive',
    keywords: ['大小写', '驼峰', '下划线', 'case'],
    path: '/text/case-converter',
    component: lazy(() => import('./text/CaseConverter')),
  },
  {
    id: 'regex-tester',
    name: '正则表达式测试',
    description: '实时验证正则匹配，高亮匹配结果',
    category: 'text',
    icon: 'Search',
    keywords: ['正则', 'regex', '匹配', 'match'],
    path: '/text/regex-tester',
    component: lazy(() => import('./text/RegexTester')),
  },
  {
    id: 'regex-cheatsheet',
    name: '正则表达式速查表',
    description: '常用正则表达式模板库，支持一键复制和在线测试',
    category: 'text',
    icon: 'BookMarked',
    keywords: ['正则', 'regex', '速查', 'cheatsheet', '模式'],
    path: '/text/regex-cheatsheet',
    component: lazy(() => import('./text/RegexCheatsheet')),
  },

  // ── 编码加密 ──
  {
    id: 'base64',
    name: 'Base64 编解码',
    description: 'Base64 文本和图片的编码与解码',
    category: 'crypto',
    icon: 'FileCode',
    keywords: ['base64', '编码', '解码'],
    path: '/crypto/base64',
    component: lazy(() => import('./crypto/Base64Tool')),
  },
  {
    id: 'url-encode',
    name: 'URL 编解码',
    description: 'URL 特殊字符的编码与解码',
    category: 'crypto',
    icon: 'Link',
    keywords: ['url', '编码', 'decode', 'encode'],
    path: '/crypto/url-encode',
    component: lazy(() => import('./crypto/UrlEncode')),
  },
  {
    id: 'unicode',
    name: 'Unicode 中文互转',
    description: 'Unicode 编码与中文字符互相转换',
    category: 'crypto',
    icon: 'Languages',
    keywords: ['unicode', '中文', '转码'],
    path: '/crypto/unicode',
    component: lazy(() => import('./crypto/UnicodeTool')),
  },
  {
    id: 'jwt-decoder',
    name: 'JWT 解析验证',
    description: '解码和验证 JSON Web Token，支持过期时间检测和实时预览',
    category: 'crypto',
    icon: 'ShieldCheck',
    keywords: ['jwt', 'token', '验证'],
    path: '/crypto/jwt-decoder',
    component: lazy(() => import('./crypto/JwtDebugger')),
  },
  {
    id: 'hash-generator',
    name: '哈希生成器',
    description: 'MD5 / SHA-1 / SHA-256 / SHA-512 等哈希计算',
    category: 'crypto',
    icon: 'Hash',
    keywords: ['hash', 'md5', 'sha', '哈希'],
    path: '/crypto/hash-generator',
    component: lazy(() => import('./crypto/HashGenerator')),
  },

  // ── 数据格式 ──
  {
    id: 'json-viewer',
    name: 'JSON 查看器',
    description: '可视化树形结构查看 JSON，支持搜索和复制路径',
    category: 'data',
    icon: 'Braces',
    keywords: ['json', 'tree', 'treeview', '查看器', '搜索'],
    path: '/data/json-viewer',
    component: lazy(() => import('./data/JsonViewer')),
  },
  {
    id: 'json-formatter',
    name: 'JSON 格式化',
    description: 'JSON 美化、压缩、验证',
    category: 'data',
    icon: 'Braces',
    keywords: ['json', '格式化', '美化', 'format'],
    path: '/data/json-formatter',
    component: lazy(() => import('./data/JsonFormatter')),
  },
  {
    id: 'json-to-csv',
    name: 'JSON ↔ CSV',
    description: 'JSON 数组与 CSV 互转',
    category: 'data',
    icon: 'Table',
    keywords: ['json', 'csv', '转换'],
    path: '/data/json-to-csv',
    component: lazy(() => import('./data/JsonToCsv')),
  },
  {
    id: 'json-to-yaml',
    name: 'JSON ↔ YAML',
    description: 'JSON 与 YAML 格式互转',
    category: 'data',
    icon: 'FileJson',
    keywords: ['json', 'yaml', '转换'],
    path: '/data/json-to-yaml',
    component: lazy(() => import('./data/JsonToYaml')),
  },
  {
    id: 'data-processor',
    name: '数据批量整理',
    description: '支持 Excel、Shapefile、CSV、JSON 文件的数据批量整理，可添加多条处理规则进行值替换',
    category: 'data',
    icon: 'Table2',
    keywords: ['数据', 'excel', 'shapefile', 'csv', '批量', '替换', '整理', 'processor'],
    path: '/data/data-processor',
    component: lazy(() => import('./data-processor')),
  },

  // ── 时间日期 ──
  {
    id: 'timestamp',
    name: '时间戳转换',
    description: 'Unix 时间戳与日期时间互转',
    category: 'datetime',
    icon: 'Clock',
    keywords: ['时间戳', 'timestamp', 'unix'],
    path: '/datetime/timestamp',
    component: lazy(() => import('./datetime/Timestamp')),
  },
  {
    id: 'date-calculator',
    name: '日期计算器',
    description: '计算日期差值，日期加减天数',
    category: 'datetime',
    icon: 'CalendarDays',
    keywords: ['日期', '计算', '差值', 'date'],
    path: '/datetime/date-calculator',
    component: lazy(() => import('./datetime/DateCalculator')),
  },
  {
    id: 'cron-generator',
    name: 'Cron 表达式生成器',
    description: '可视化生成 Cron 表达式，预览最近执行时间',
    category: 'datetime',
    icon: 'CalendarClock',
    keywords: ['cron', '定时', '调度', 'schedule'],
    path: '/datetime/cron-generator',
    component: lazy(() => import('./datetime/CronGenerator')),
  },

  // ── 网络工具 ──
  {
    id: 'ip-lookup',
    name: 'IP 地址查询',
    description: '查询 IP 地址的地理位置和运营商信息',
    category: 'network',
    icon: 'MapPin',
    keywords: ['ip', '地址', '位置', 'location'],
    path: '/network/ip-lookup',
    component: lazy(() => import('./network/IpLookup')),
  },
  {
    id: 'ua-parser',
    name: 'User-Agent 解析',
    description: '解析 User-Agent 字符串，提取浏览器和系统信息',
    category: 'network',
    icon: 'Monitor',
    keywords: ['ua', 'user-agent', '浏览器'],
    path: '/network/ua-parser',
    component: lazy(() => import('./network/UaParser')),
  },

  // ── 图像工具 ──
  {
    id: 'image-compressor',
    name: '图片压缩',
    description: '纯前端图片压缩，支持质量调节',
    category: 'image',
    icon: 'Minimize2',
    keywords: ['图片', '压缩', 'compress'],
    path: '/image/image-compressor',
    component: lazy(() => import('./image/ImageCompressor')),
  },
  {
    id: 'base64-image',
    name: 'Base64 ↔ 图片',
    description: 'Base64 字符串与图片互转',
    category: 'image',
    icon: 'ImagePlus',
    keywords: ['base64', '图片', '转换'],
    path: '/image/base64-image',
    component: lazy(() => import('./image/Base64Image')),
  },

  // ── 代码工具 ──
  {
    id: 'code-formatter',
    name: '代码格式化',
    description: 'HTML / CSS / JS / JSON / SQL 代码美化',
    category: 'code',
    icon: 'Code2',
    keywords: ['格式化', '美化', 'format', 'prettier'],
    path: '/code/code-formatter',
    component: lazy(() => import('./code/CodeFormatter')),
  },
  {
    id: 'html-markdown',
    name: 'HTML ↔ Markdown',
    description: 'HTML 和 Markdown 格式互转',
    category: 'code',
    icon: 'FileText',
    keywords: ['html', 'markdown', '转换'],
    path: '/code/html-markdown',
    component: lazy(() => import('./code/HtmlMarkdown')),
  },
  {
    id: 'api-doc-generator',
    name: 'API 文档生成器',
    description: '根据 JSON Schema 或示例 JSON 生成 Markdown / OpenAPI / HTML 文档',
    category: 'code',
    icon: 'FileText',
    keywords: ['api', '文档', 'openapi', 'swagger', 'markdown', 'html', 'json schema'],
    path: '/code/api-doc-generator',
    component: lazy(() => import('./code/ApiDocGenerator')),
  },

  {
    id: 'id-card-lookup',
    name: '身份证信息查询',
    description: '输入身份证号码，解析户籍所在地、出生日期、性别、年龄、生肖等信息',
    category: 'common',
    icon: 'CreditCard',
    keywords: ['身份证', 'idcard', '身份证查询', '身份信息'],
    path: '/common/id-card-lookup',
    component: lazy(() => import('./common/IdCardLookup')),
  },

  // ── 常用工具（新增） ──
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum 生成器',
    description: '生成占位文本，支持英文和中文',
    category: 'common',
    icon: 'AlignJustify',
    keywords: ['lorem', '占位', '假文', 'dummy text'],
    path: '/common/lorem-ipsum',
    component: lazy(() => import('./common/LoremIpsum')),
  },
  {
    id: 'random-data-generator',
    name: '随机数据生成器',
    description: '生成 Mock 测试数据，支持姓名、邮箱、手机号、地址等多种类型',
    category: 'common',
    icon: 'Shuffle',
    keywords: ['随机', 'mock', '测试数据', '姓名', '邮箱', '手机号', 'random', 'data'],
    path: '/common/random-data-generator',
    component: lazy(() => import('./common/RandomDataGenerator')),
  },
  {
    id: 'mobile-lookup',
    name: '手机号归属地查询',
    description: '查询手机号码的运营商、归属地、区号和邮编信息',
    category: 'common',
    icon: 'Smartphone',
    keywords: ['手机号', '归属地', '运营商', '电话号码', 'mobile', 'phone'],
    path: '/common/mobile-lookup',
    component: lazy(() => import('./common/MobileLookup')),
  },
  {
    id: 'bank-card-lookup',
    name: '银行卡信息查询',
    description: '输入银行卡号查询发卡行、卡类型和卡组织',
    category: 'common',
    icon: 'CreditCard',
    keywords: ['银行卡', 'bin', 'bank', '信用卡', '储蓄卡', '银联', 'visa'],
    path: '/common/bank-card-lookup',
    component: lazy(() => import('./common/BankCardLookup')),
  },
  {
    id: 'zh-converter',
    name: '简繁转换',
    description: '简体与繁体中文互转，支持常用词组和多音字处理',
    category: 'common',
    icon: 'Languages',
    keywords: ['简体', '繁体', '转换', '中文', '简繁', '繁简'],
    path: '/common/zh-converter',
    component: lazy(() => import('./common/ZhConverter')),
  },

  // ── 文本处理（新增） ──
  {
    id: 'text-dedup',
    name: '文本去重',
    description: '按行、按词、按字符去除重复内容',
    category: 'text',
    icon: 'CopyMinus',
    keywords: ['去重', '重复', 'dedup', 'unique'],
    path: '/text/text-dedup',
    component: lazy(() => import('./text/TextDedup')),
  },
  {
    id: 'text-sort',
    name: '文本排序',
    description: '按行排序，支持升序/降序、数字/文本模式',
    category: 'text',
    icon: 'ArrowDownUp',
    keywords: ['排序', 'sort', '升序', '降序'],
    path: '/text/text-sort',
    component: lazy(() => import('./text/TextSort')),
  },
  {
    id: 'text-diff',
    name: '文本 Diff 对比',
    description: '逐行对比两段文本的差异',
    category: 'text',
    icon: 'GitCompare',
    keywords: ['diff', '对比', '比较', 'compare'],
    path: '/text/text-diff',
    component: lazy(() => import('./text/TextDiff')),
  },
  {
    id: 'markdown-preview',
    name: 'Markdown 预览',
    description: '实时 Markdown 编辑预览，支持语法高亮',
    category: 'text',
    icon: 'FileText',
    keywords: ['markdown', 'md', '预览', 'preview', '编辑', '编辑器'],
    path: '/text/markdown-preview',
    component: lazy(() => import('./text/MarkdownPreview')),
  },
  {
    id: 'symbols',
    name: '特殊符号',
    description: '常用符号大全，支持搜索和复制，包含希腊字母、数学、箭头等12个分类',
    category: 'text',
    icon: 'Star',
    keywords: ['符号', '特殊符号', '希腊字母', '数学符号', '箭头', 'emoji', '标点', 'currency'],
    path: '/text/symbols',
    component: lazy(() => import('./text/Symbols')),
  },

  // ── 编码加密（新增） ──
  {
    id: 'hmac-generator',
    name: 'HMAC 生成器',
    description: '使用密钥计算 HMAC 哈希值',
    category: 'crypto',
    icon: 'KeySquare',
    keywords: ['hmac', '密钥', '签名'],
    path: '/crypto/hmac-generator',
    component: lazy(() => import('./crypto/HmacGenerator')),
  },
  {
    id: 'aes-rsa-tool',
    name: 'AES/RSA 加解密',
    description: 'AES 对称加密和 RSA 非对称加密，使用 Web Crypto API',
    category: 'crypto',
    icon: 'KeySquare',
    keywords: ['aes', 'rsa', '加密', '解密', '对称', '非对称', 'encrypt', 'decrypt'],
    path: '/crypto/aes-rsa-tool',
    component: lazy(() => import('./crypto/AesRsaTool')),
  },
  {
    id: 'password-strength',
    name: '密码强度检测',
    description: '检测密码安全等级并生成强密码',
    category: 'crypto',
    icon: 'Shield',
    keywords: ['密码', '强度', '安全', 'password', 'strength'],
    path: '/crypto/password-strength',
    component: lazy(() => import('./crypto/PasswordStrength')),
  },
  {
    id: 'html-entity',
    name: 'HTML 实体编解码',
    description: 'HTML 特殊字符实体编码与解码',
    category: 'crypto',
    icon: 'Brackets',
    keywords: ['html', 'entity', '实体', '转义'],
    path: '/crypto/html-entity',
    component: lazy(() => import('./crypto/HtmlEntity')),
  },

  // ── 数据格式（新增） ──
  {
    id: 'xml-json-converter',
    name: 'XML ↔ JSON',
    description: 'XML 与 JSON 格式互转，支持属性和 CDATA',
    category: 'data',
    icon: 'FileCode',
    keywords: ['xml', 'json', '转换', 'converter'],
    path: '/data/xml-json-converter',
    component: lazy(() => import('./data/XmlJsonConverter')),
  },
  {
    id: 'csv-excel-converter',
    name: 'CSV ↔ Excel',
    description: 'CSV 与 Excel 文件互转，支持分隔符和编码设置',
    category: 'data',
    icon: 'Table',
    keywords: ['csv', 'excel', 'xlsx', '转换', 'converter', '表格'],
    path: '/data/csv-excel-converter',
    component: lazy(() => import('./data/CsvExcelConverter')),
  },
  {
    id: 'sql-formatter',
    name: 'SQL 格式化',
    description: 'SQL 语句美化与格式化',
    category: 'data',
    icon: 'Database',
    keywords: ['sql', '格式化', '美化', 'database'],
    path: '/data/sql-formatter',
    component: lazy(() => import('./data/SqlFormatter')),
  },

  // ── 时间日期（新增） ──
  {
    id: 'timezone',
    name: '时区转换',
    description: '在不同时区之间转换时间',
    category: 'datetime',
    icon: 'Globe',
    keywords: ['时区', 'timezone', '转换'],
    path: '/datetime/timezone',
    component: lazy(() => import('./datetime/Timezone')),
  },
  {
    id: 'workday-calc',
    name: '工作日计算',
    description: '计算日期间工作日数，或加减工作日',
    category: 'datetime',
    icon: 'Briefcase',
    keywords: ['工作日', 'workday', '上班'],
    path: '/datetime/workday-calc',
    component: lazy(() => import('./datetime/WorkdayCalc')),
  },
  {
    id: 'cron-interpreter',
    name: 'Cron 表达式解释器',
    description: '解析 Cron 表达式含义，查看未来执行时间',
    category: 'datetime',
    icon: 'CalendarClock',
    keywords: ['cron', '解释', 'parse', 'schedule'],
    path: '/datetime/cron-interpreter',
    component: lazy(() => import('./datetime/CronInterpreter')),
  },

  // ── 网络工具（新增） ──
  {
    id: 'http-tester',
    name: 'HTTP 请求测试',
    description: 'API 接口调试工具，支持多种请求方法',
    category: 'network',
    icon: 'Send',
    keywords: ['http', 'api', '请求', '接口'],
    path: '/network/http-tester',
    component: lazy(() => import('./network/HttpTester')),
  },
  {
    id: 'websocket-tester',
    name: 'WebSocket 测试器',
    description: '调试 WebSocket 连接，实时发送和接收消息',
    category: 'network',
    icon: 'Wifi',
    keywords: ['websocket', 'ws', 'wss', '连接', '调试'],
    path: '/network/websocket-tester',
    component: lazy(() => import('./network/WebSocketTester')),
  },
  {
    id: 'dns-lookup',
    name: 'DNS 查询',
    description: '通过 DNS over HTTPS 查询域名解析记录',
    category: 'network',
    icon: 'Server',
    keywords: ['dns', '域名', '解析', 'lookup'],
    path: '/network/dns-lookup',
    component: lazy(() => import('./network/DnsLookup')),
  },
  {
    id: 'url-parser',
    name: 'URL 解析器',
    description: '解析 URL 各组成部分和查询参数',
    category: 'network',
    icon: 'Link2',
    keywords: ['url', '解析', '参数', 'query'],
    path: '/network/url-parser',
    component: lazy(() => import('./network/UrlParser')),
  },
  {
    id: 'url-unshortener',
    name: '短链接还原',
    description: '追踪短链接重定向，显示完整跳转链和最终目标地址',
    category: 'network',
    icon: 'Link',
    keywords: ['短链接', 'unshorten', 'redirect', 't.cn', 'bit.ly', 'tinyurl'],
    path: '/network/url-unshortener',
    component: lazy(() => import('./network/UrlUnshortener')),
  },
  {
    id: 'github-accelerator',
    name: 'GitHub 加速',
    description: '将 GitHub 下载链接转换为镜像加速地址，支持多种镜像源',
    category: 'network',
    icon: 'Rocket',
    keywords: ['github', '加速', '镜像', 'download', 'proxy'],
    path: '/network/github-accelerator',
    component: lazy(() => import('./network/Github加速')),
  },

  // ── 图像工具（新增） ──
  {
    id: 'image-crop',
    name: '图片裁剪',
    description: '上传图片，指定区域裁剪',
    category: 'image',
    icon: 'Crop',
    keywords: ['裁剪', 'crop', '截图'],
    path: '/image/image-crop',
    component: lazy(() => import('./image/ImageCrop')),
  },
  {
    id: 'svg-optimizer',
    name: 'SVG 优化器',
    description: '压缩、清理、格式化 SVG 文件',
    category: 'image',
    icon: 'Minimize2',
    keywords: ['svg', '优化', '压缩', 'optimize', 'compress'],
    path: '/image/svg-optimizer',
    component: lazy(() => import('./image/SvgOptimizer')),
  },
  {
    id: 'base64-image-viewer',
    name: 'Base64 图片预览',
    description: 'Base64 字符串转图片预览，支持拖拽上传和多种格式检测',
    category: 'image',
    icon: 'Eye',
    keywords: ['base64', '图片', '预览', 'viewer', '查看'],
    path: '/image/base64-image-viewer',
    component: lazy(() => import('./image/Base64ImageViewer')),
  },
  {
    id: 'image-to-ico',
    name: '图片转 ICO',
    description: '将图片转换为 Windows ICO 图标格式，支持多种尺寸',
    category: 'image',
    icon: 'ImageIcon',
    keywords: ['ico', '图标', 'icon', 'windows', '图片转换'],
    path: '/image/image-to-ico',
    component: lazy(() => import('./image/ImageToIco')),
  },

  // ── 前端开发（新增分类） ──
  {
    id: 'color-picker',
    name: '颜色工具',
    description: '颜色选择、格式转换、对比度检查',
    category: 'frontend',
    icon: 'Palette',
    keywords: ['颜色', 'color', '对比度', 'picker'],
    path: '/frontend/color-picker',
    component: lazy(() => import('./frontend/ColorPicker')),
  },
  {
    id: 'rgb-color-table',
    name: '颜色参考表',
    description: '颜色调色板，支持 HEX/RGB/HSL 格式转换和复制',
    category: 'frontend',
    icon: 'Palette',
    keywords: ['颜色', 'color', 'rgb', 'hex', 'hsl', '参考表', '调色板'],
    path: '/frontend/rgb-color-table',
    component: lazy(() => import('./frontend/RgbColorTable')),
  },
  {
    id: 'css-shadow',
    name: 'CSS 阴影生成器',
    description: '可视化生成 box-shadow 代码',
    category: 'frontend',
    icon: 'SquareShadow',
    keywords: ['阴影', 'shadow', 'box-shadow'],
    path: '/frontend/css-shadow',
    component: lazy(() => import('./frontend/CssShadow')),
  },
  {
    id: 'flexbox-playground',
    name: 'Flexbox 布局生成器',
    description: '可视化调整 Flexbox 属性，实时预览并生成代码',
    category: 'frontend',
    icon: 'LayoutGrid',
    keywords: ['flexbox', '布局', 'flex', 'css'],
    path: '/frontend/flexbox-playground',
    component: lazy(() => import('./frontend/FlexboxPlayground')),
  },

  // ── 休闲娱乐 ──
  {
    id: 'minesweeper',
    name: '扫雷',
    description: '经典扫雷游戏，点击揭开安全区域，右键标记地雷',
    category: 'entertainment',
    icon: 'Bomb',
    keywords: ['扫雷', 'minesweeper', '雷', 'mine'],
    path: '/entertainment/minesweeper',
    component: lazy(() => import('./entertainment/Minesweeper')),
  },
  {
    id: 'ascii-banner',
    name: 'ASCII Banner 生成器',
    description: '将文本转换为ASCII艺术字，支持多种字体样式',
    category: 'entertainment',
    icon: 'Type',
    keywords: ['ASCII', 'banner', '艺术字', '字体', 'text'],
    path: '/entertainment/ascii-banner',
    component: lazy(() => import('./entertainment/AsciiBanner')),
  },

  // ── GIS 地图 ──
  {
    id: 'shapefile-converter',
    name: 'Shapefile 解析与导出',
    description: '解析 Shapefile (.shp/.dbf/.prj) 或 ZIP 压缩包，查看属性表格并导出',
    category: 'gis',
    icon: 'Map',
    keywords: ['shapefile', 'shp', 'dbf', 'prj', 'gis', '解析', '导出', '属性表'],
    path: '/gis/shapefile-converter',
    component: lazy(() => import('./gis/ShapefileConverter')),
  },
  {
    id: 'map-viewer',
    name: '地图文件查看器',
    description: '在线解析 Shapefile / GeoJSON，地图可视化展示',
    category: 'gis',
    icon: 'Map',
    keywords: ['地图', 'shapefile', 'geojson', 'shp', 'map', '可视化'],
    path: '/gis/map-viewer',
    component: lazy(() => import('./gis/MapViewer')),
  },
  {
    id: 'area-calculator',
    name: '多边形面积计算',
    description: '绘制或导入多边形，计算面积和周长',
    category: 'gis',
    icon: 'Pentagon',
    keywords: ['面积', '多边形', '周长', 'area', 'polygon'],
    path: '/gis/area-calculator',
    component: lazy(() => import('./gis/AreaCalculator')),
  },
  {
    id: 'distance-calculator',
    name: '距离测量',
    description: '地图点击测距或坐标输入计算距离',
    category: 'gis',
    icon: 'Route',
    keywords: ['距离', '测距', 'distance', '测量'],
    path: '/gis/distance-calculator',
    component: lazy(() => import('./gis/DistanceCalculator')),
  },
  {
    id: 'coordinate-converter',
    name: '坐标系转换',
    description: 'WGS84 / GCJ-02 / BD-09 / Mercator 坐标互转',
    category: 'gis',
    icon: 'ArrowLeftRight',
    keywords: ['坐标', 'WGS84', 'GCJ02', 'BD09', '火星坐标', '百度坐标', '转换'],
    path: '/gis/coordinate-converter',
    component: lazy(() => import('./gis/CoordinateConverter')),
  },
  {
    id: 'geojson-editor',
    name: 'GeoJSON 编辑器',
    description: '在线编辑、验证、预览 GeoJSON 数据',
    category: 'gis',
    icon: 'FileJson',
    keywords: ['geojson', '编辑', '验证', 'json', '地图'],
    path: '/gis/geojson-editor',
    component: lazy(() => import('./gis/GeoJsonEditor')),
  },
  {
    id: 'bounding-box',
    name: '边界框工具',
    description: '生成和可视化地理边界框，支持多种格式输出',
    category: 'gis',
    icon: 'Box',
    keywords: ['边界框', 'bbox', 'bounding box', '范围'],
    path: '/gis/bounding-box',
    component: lazy(() => import('./gis/BoundingBox')),
  },
  {
    id: 'coordinate-picker',
    name: '地图坐标拾取',
    description: '点击地图获取坐标，支持 WGS84/DMS/UTM 多种格式',
    category: 'gis',
    icon: 'MapPin',
    keywords: ['坐标', '拾取', '地图', 'WGS84', 'DMS', 'UTM', 'picker'],
    path: '/gis/coordinate-picker',
    component: lazy(() => import('./gis/CoordinatePicker')),
  },

  // ── 休闲娱乐 ──
  {
    id: 'super-mario',
    name: '超级马里奥',
    description: '经典平台跳跃游戏，踩敌人、吃金币、收集道具',
    category: 'entertainment',
    icon: 'Gamepad2',
    keywords: ['马里奥', '超级玛丽', 'platformer', 'platform', '游戏', '跳跃'],
    path: '/entertainment/super-mario',
    component: lazy(() => import('./entertainment/SuperMario')),
  },
  {
    id: 'aircraft-battle',
    name: '飞机大战',
    description: '经典垂直射击游戏，击落敌机获取分数，支持多种敌人类型和道具',
    category: 'entertainment',
    icon: 'Plane',
    keywords: ['飞机', '射击', '游戏', '飞机大战', 'aircraft', 'battle', 'shooter'],
    path: '/entertainment/aircraft-battle',
    component: lazy(() => import('./entertainment/AircraftBattle')),
  },
  {
    id: 'black-hole',
    name: '黑洞吞噬',
    description: '控制黑洞吸引并吞噬物体，避开危险物体，连击获得高分！',
    category: 'entertainment',
    icon: 'Circle',
    keywords: ['黑洞', '吞噬', '游戏', '物理', '引力', 'space', 'gravity'],
    path: '/entertainment/black-hole',
    component: lazy(() => import('./entertainment/BlackHole')),
  },

  // ── AI 对话 ──
  {
    id: 'ai-chat',
    name: 'AI 对话',
    description: 'AI 对话工具，支持多种模型流式输出',
    category: 'ai',
    icon: 'Bot',
    keywords: ['AI', 'ChatGPT', 'GPT', '对话', 'ai', 'chat', 'gpt'],
    path: '/ai/chat',
    component: lazy(() => import('./ai/AiChat')),
  },
]

// ============================================================
// 注册表导出
// ============================================================

export const allTools: ToolManifest[] = toolModules

/** 按分类获取工具 */
export function getToolsByCategory(categoryId: string): ToolManifest[] {
  return toolModules.filter((t) => t.category === categoryId)
}

/** 通过 id 获取工具 */
export function getToolById(id: string): ToolManifest | undefined {
  return toolModules.find((t) => t.id === id)
}

/** 通过路径获取工具 */
export function getToolByPath(path: string): ToolManifest | undefined {
  return toolModules.find((t) => t.path === path)
}

/** 全局搜索 */
export function searchTools(query: string): ToolManifest[] {
  const q = query.toLowerCase().trim()
  if (!q) return []
  return toolModules.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.toLowerCase().includes(q))
  )
}
